### ISSUE TITLE
SQL语句 SELECT *

### ISSUE THREAD

**Issue by mzdora** [macrozhang/LearningSystem#1]
给个小建议，用SELECT *会增加数据库负担，很多地方都没必要全部查询。
码问就对数据库进行了一些优化，
但是咋们这个数据量比较小，所以也无所谓啦 👍

**Comment by macrozhang** [comment]
哈哈哈👌
看到评论的我不禁有点出戏😂

**Comment by macrozhang** [comment]
这些方面我不熟悉，这次多亏了友人相助才能渡劫。
不过还需要抽时间好好学学，谢谢建议 😄
以后多多评论哈~

> 给个小建议，用SELECT *会增加数据库负担，很多地方都没必要全部查询。
> 码问就对数据库进行了一些优化，
> 但是咋们这个数据量比较小，所以也无所谓啦 👍
